### ISSUE TITLE
Toolbar not showing

### ISSUE THREAD

**Issue by andfinally** [iseulde/wp-front-end-editor#233] opened 2015-03-23 20:59 UTC
Hi, I've tried out the plugin on my local installation with the Twenty Fifteen and Twenty Twelve themes. I activate the plugin and click on body text, headline and other parts of the single post page in my site, but nothing happens. I get the same thing on pages. There are no JS errors. Am I misunderstanding how the plugin's supposed to work?

Thanks!

**Comment by iseulde** [comment] 2016-07-05 17:00
You should click on "edit post" in the admin bar. This will change though, it's a bit too hidden.

**Comment by andfinally** [comment] 2016-07-06 08:07
Thanks! I'll try that.

**Comment by andfinally** [comment] 2016-07-06 08:16
Unfortunately it's still not working for me - I'm getting these JS errors when I activate the plugin. I see a new addition to the "Edit Post" link in the admin bar which says "Edit in admin". But clicking "Edit Post" does nothing. 

tinymce.image.js?ver=1.1.0:3 Uncaught ReferenceError: tinymce is not defined(anonymous function) @ tinymce.image.js?ver=1.1.0:3
tinymce.insert.js?ver=1.1.0:3 Uncaught ReferenceError: tinymce is not defined(anonymous function) @ tinymce.insert.js?ver=1.1.0:3
tinymce.theme.js?ver=1.1.0:3 Uncaught ReferenceError: tinymce is not defined(anonymous function) @ tinymce.theme.js?ver=1.1.0:3
wp-auth-check.min.js?ver=4.6-alpha-37690:1 Uncaught TypeError: Cannot read property 'hasClass' of undefined(anonymous function) @ wp-auth-check.min.js?ver=4.6-alpha-37690:1dispatch @ jquery.js?ver=1.12.4:3r.handle @ jquery.js?ver=1.12.4:3trigger @ jquery.js?ver=1.12.4:3a.event.trigger @ jquery-migrate.min.js?ver=1.4.1:2(anonymous function) @ jquery.js?ver=1.12.4:3each @ jquery.js?ver=1.12.4:2each @ jquery.js?ver=1.12.4:2trigger @ jquery.js?ver=1.12.4:3(anonymous function) @ heartbeat.min.js?ver=4.6-alpha-37690:1i @ jquery.js?ver=1.12.4:2fireWith @ jquery.js?ver=1.12.4:2y @ jquery.js?ver=1.12.4:4c @ jquery.js?ver=1.12.4:4
mce-view-register.js?ver=1.1.0:187 Uncaught TypeError: Cannot read property 'views' of undefined

**Comment by iseulde** [comment] 2016-07-06 08:19
Thank for the feedback. I'm working on fixes and will release in a few days. May I ask what WP version you have?

**Comment by andfinally** [comment] 2016-07-06 08:22
Thanks iseulde. I realised I didn't have the latest version of the plugin - installed plugin version 2.3.1 and switched to Twenty Fifteen theme. With that setup the JS errors I mentioned disappear, but the plugin doesn't seem to take over the Edit Post link - clicking it just takes me to the normal post edit form.

I am on WP 4.5.3.

**Comment by iseulde** [comment] 2016-07-06 08:29
This plugin version only goes to 1.1.0 :)

**Comment by andfinally** [comment] 2016-07-06 08:29
Oh sorry, I didn't spot that! I will close this one. Thanks!

**Comment by iseulde** [comment] 2016-07-06 08:31
Was it another plugin then? Or does it work fine now?

**Comment by andfinally** [comment] 2016-07-06 09:06
Oh sorry, I'm confused - I thought you meant the plugin supports only up to WP 1.1.0! Thought that was a bit old! This is the upgrade prompt I see in wp-admin/plugins when I go to activate the plugin, and here are the details, showing it goes up to 2.3.1.

Thanks!
![front-end-editor-1](https://cloud.githubusercontent.com/assets/1647564/16612908/58344362-4361-11e6-946e-bfb38c382af9.png)
![front-end-editor](https://cloud.githubusercontent.com/assets/1647564/16612907/5830a9b4-4361-11e6-99b9-151be1049902.png)

**Comment by iseulde** [comment] 2016-07-06 09:10
Hm that's weird. When you click _edit_, what's the first file you see under _Plugin Files_?

**Comment by andfinally** [comment] 2016-07-06 09:41
It's wp-front-end-editor-master/plugin.php, contents look legit:

```
<?php

/*
 * Plugin Name: Front-end Editor
 * Plugin URI:  https://wordpress.org/plugins/wp-front-end-editor/
 * Description: Edit your posts on the front-end of your site.
 * Version:     1.1.0
 * Author:      Ella Iseulde Van Dorpe
 * Author URI:  https://iseulde.com
 * Text Domain: wp-front-end-editor
 * Domain Path: languages
 * Network:     false
 * License:     GPL-2.0+
 */

if ( ! class_exists( 'FEE' ) ) {
	require_once 'class-fee.php';
	$GLOBALS['wp_front_end_editor'] = new FEE;
}
```

**Comment by iseulde** [comment] 2016-07-06 11:10
Hm, why is it wp-front-end-editor**-master**? That's likely the confusing bit for the upgrader. If it can't match the folder it will try to match the name.

**Comment by christianwach** [comment] 2016-07-06 11:14
> why is it wp-front-end-editor-master

FWIW, that's what happens when there's been a download of the ZIP file for the master branch from this GitHub repo. The enclosing folder should be renamed by the downloader before adding the plugin to WordPress, but this appears to have been overlooked.

**Comment by iseulde** [comment] 2016-07-06 11:17
This is a problem in core/.org really, they shouldn't try to match plugin titles. I think it makes sense to adjust the title and/or the folder when a 2.x version is published, just so it's less confusing.

**Comment by andfinally** [comment] 2016-07-06 11:22
Ah well spotted! Yes, I copied the expanded zip straight into wp-content/plugins.

OK, so now I've renamed the folder, reactivated the plugin and switched to Twenty Fifteen. Unfortunately I'm now getting similar JS errors as before, and although I see the addition of the "Edit in admin" link to the Edit Post link, clicking Edit Post doesn't do anything - the FE edit feature isn't active.

tinymce.image.js?ver=1.1.0:3 Uncaught ReferenceError: tinymce is not defined(anonymous function) @ tinymce.image.js?ver=1.1.0:3
tinymce.insert.js?ver=1.1.0:3 Uncaught ReferenceError: tinymce is not defined(anonymous function) @ tinymce.insert.js?ver=1.1.0:3
tinymce.theme.js?ver=1.1.0:3 Uncaught ReferenceError: tinymce is not defined(anonymous function) @ tinymce.theme.js?ver=1.1.0:3
wp-auth-check.min.js?ver=4.6-alpha-37690:1 Uncaught TypeError: Cannot read property 'hasClass' of undefined(anonymous function) @ wp-auth-check.min.js?ver=4.6-alpha-37690:1dispatch @ jquery.js?ver=1.12.4:3r.handle @ jquery.js?ver=1.12.4:3trigger @ jquery.js?ver=1.12.4:3a.event.trigger @ jquery-migrate.min.js?ver=1.4.1:2(anonymous function) @ jquery.js?ver=1.12.4:3each @ jquery.js?ver=1.12.4:2each @ jquery.js?ver=1.12.4:2trigger @ jquery.js?ver=1.12.4:3(anonymous function) @ heartbeat.min.js?ver=4.6-alpha-37690:1i @ jquery.js?ver=1.12.4:2fireWith @ jquery.js?ver=1.12.4:2y @ jquery.js?ver=1.12.4:4c @ jquery.js?ver=1.12.4:4
mce-view-register.js?ver=1.1.0:187 Uncaught TypeError: Cannot read property 'views' of undefined(anonymous function) @ mce-view-register.js?ver=1.1.0:187
fee.js?ver=1.1.0:6 Uncaught TypeError: Cannot read property 'util' of undefined

**Comment by iseulde** [comment] 2016-07-06 11:31
Okay. As you've already downloaded it from GitHub before, maybe it's worth downloading the master, renaming it, and uploading it to your site? The issues are likely to be resolved by now, and it's easier for me to fix any remaining issues rather than fixing the old version and trying to do a minor release for that. I'm happy to fix any issues you have with that one with priority.

Alternatively you could wait until I update the plugin and then update the plugin on your site. Not sure when it will be, but soon.

**Comment by andfinally** [comment] 2016-07-06 11:35
Thanks iseulde - master is the version I'm working with. No worries, I'm happy to wait for whenever the next version comes out - if you don't mind I'll leave this open as a reminder to myself to try the next version. Good luck!

**Comment by iseulde** [comment] 2016-07-06 11:40
Ah, okay. Sorry I thought you were updating to the wp.org version. I just tried what you did and I know the problem now. GitHub does not clone the submodules and they are empty. I'll see what I can do right now.

**Comment by andfinally** [comment] 2016-07-06 11:41
Great, thank you!

**Comment by iseulde** [comment] 2016-07-06 14:15
@andfinally Should work now after 8dd4ff04e163d6801ac5edcd494307f4ceefecac.

**Comment by andfinally** [comment] 2016-07-06 16:51
Thanks iseulde - I'm getting closer - I see the Update and Cancel links - but when I click on Edit Post I get this alert, and I'm unable to do anything else.

![front-end-edit](https://cloud.githubusercontent.com/assets/1647564/16626619/a5cd0830-43a1-11e6-928f-a58fbd92fb7e.jpg)

**Comment by iseulde** [comment] 2016-07-06 16:52
What happens if you click cancel? Sorry will fix asap.

**Comment by andfinally** [comment] 2016-07-06 16:55
I'm not able to click on Edit Post > Cancel - the confirm pops up as soon as I click on Edit Post, and when I click OK or Cancel on that, the Update and Cancel links disappear from Edit Post.

No rush, I'm happy to hang on till whenever you have a chance to look at it, thanks!

**Comment by iseulde** [comment] 2016-07-07 20:38
Should be gone after 03cf6cc04c85fffc5f49557557d01ead06d775f7. Please note that this repository is a work in progress until there's a new release. I'd love people trying and testing it though!

**Comment by andfinally** [comment] 2016-07-08 08:25
Joy! Thanks a lot, it's working fine in Twenty Fifteen!

My next challenge is to get it to work with my own theme - with that active I'm getting the occasional error 

Uncaught TypeError: wp.api.models[(intermediate value)(intermediate value)(intermediate value)] is not a constructor fee.js?ver=2.0.0-alpha:51

And I'm unable to make changes. When I get a plain text post that does seem to accept it, I click the Edit Post button - I don't see the extra options but the link text goes blue suggesting it's active. When I make changes to the text they appear in the page. But when I click the Edit Post button again or try to navigate back to the standard view of the post I get the alert "The changes you made will be lost if you navigate away from this page.", and the change isn't saved.

But thanks for fixing this one - it's a great plugin!

**Comment by iseulde** [comment] 2016-07-08 08:34
Let's keep this open then, your theme should work too. :)

What theme do you have? Is there a link to it, or did you make it?

Not sure why you're getting the error. If you have the rest API installed (as the plugin will prompt you to do), then that constructor should be available.

The alert if only temporary, this will go away in the next commit which will be today. Then the saving will work a bit differently. For now you have to click save, then 'no' when it asks to publish, and then 'yes' if you navigate away (no changes will be lost if you just saved). After the next commit saving will happen automatically, you only have to use it for publishing. I'll also add some extra sanity checking to make sure everything actually saves.

**Comment by andfinally** [comment] 2016-07-08 08:58
It's a custom theme used on a fairly big media site, so not public, unfortunately. Our site is hosted on Wordpress.com VIP, so although we have the WP Rest API plugin locally (where I am testing), on production the API is handled by WP.com at public-api.wordpress.com/rest/v1.1/sites.

Thanks for all your work on this!

**Comment by iseulde** [comment] 2016-07-08 09:38
Okay. If you can install this plugin, you can also install .org's REST API though? Having both should be fine, and eventually they will be merged. But if .com's API needs to be used this should not be that difficult soon. And I'll add some docs.

But back to the local install. If `wp.api.models.Post` or `wp.api.models.Page` is not available it means the `wp-api` script is missing? If it works for a different theme on the same install though, it should error there too, because you have the same REST API plugin installed when testing either theme?

FYI the script `wp-api.js` needs to be available and registered. https://github.com/WP-API/WP-API

**Comment by iseulde** [comment] 2016-07-08 16:41
I think your problem might be solved after 17dd3c2.

**Comment by andfinally** [comment] 2016-07-08 17:08
This is great, we're getting closer and closer! I'd just be delighted if we could get it to work on my local. When I click the Edit Post link it goes blue, the elements rendered from shortcodes in my post (like video embeds) change back into shortcodes, and I'm able to modify the post content. But I'm not sure how to save my changes. When I click Edit Post again it goes back to white, and the previous version of the content appears.

**Comment by iseulde** [comment] 2016-07-08 17:14
<img width="145" alt="screen shot 2016-07-08 at 19 14 06" src="https://cloud.githubusercontent.com/assets/4710635/16695447/3459ea42-4540-11e6-813f-a357dc558888.png">

You should see this.

**Comment by andfinally** [comment] 2016-07-08 17:20
No worries, I appreciate all the work you're putting into this! I'm not seeing the toolbar, no. I did see it at one point when I was trying one of the earlier versions today, but not with this one. I'm not seeing any JS errors. I also left it more than a minute, but the changes weren't saved.

**Comment by iseulde** [comment] 2016-07-09 19:42
Weird. We'll see once I'm done and start testing other themes. Haven't been able to reproduce so far.

**Comment by iseulde** [comment] 2016-08-02 19:10
Is this still an issue with the latest master? Needs to be resolved before releasing.

**Comment by iseulde** [comment] 2016-08-06 18:21
It seems to work fine here. Tested several themes. Could you open a new ticket if this happens again? Thanks!

**Closed by iseulde** 2016-08-06 18:21 UTC
Labels: Bug

**Comment by andfinally** [comment] 2016-08-12 09:45
Hi iseulde, I've just tested on local with my previously problematic theme and it's working well now, thank you!
