### ISSUE TITLE
Categories and tags in WP Front-End Editor, like the ones available in PressThis

### ISSUE THREAD

**Issue by picajoso** [iseulde/wp-front-end-editor#297] opened 2016-08-10 11:38 UTC
I'm using the "Press This" bookmarklet in other blog I've got and the editing options are not so nice as 1.x versions of WP Front-end Editor, but there's something I really like: the ability to add category and tags straight from there:

![pressthis](https://cloud.githubusercontent.com/assets/853760/17552313/7eafd010-5eff-11e6-9bbf-d1ff694061af.jpg)

This allows to avoid going to the native WP Editor to add categories and tags from there, what would lead to publish the post straight away. Maybe something like that could be added to WP Front-End Editor, but this is a very personal note. Maybe others are not interested in this.

**Comment by iseulde** [comment] 2016-08-10 11:40
Duplicate of #254 I think.

**Closed by iseulde** 2016-08-10 11:40 UTC
